### ISSUE TITLE
Poprawienie typu argumentow korzen w funkcjach

### ISSUE THREAD

**Issue by pieniadz1013** [pieniadz1013/INPG-baza-danych-wycieczki-#16]
Tak jak Ania mowila, trzeba chyba bedzie poprawic funkcje, tak zeby typem argumentu korzen byl Wezel, a nie Drzewo

**Comment by pieniadz1013** [comment]
Wydaje mi się, że teraz jest dobrze, dzisiaj pozostaje już tylko napisać maina, a za poprawianie i łączenie zabierzemy się w przyszłym tygodniu

**Comment by JestemAnia** [comment]
W mainie raczej tylko będzie wywoływana funkcja menu, czy coś mi umknęło?

**Comment by JestemAnia** [comment]
Tzn żeby ją wywołać to najpierw trzeba stworzyć korzeń

**Comment by JestemAnia** [comment]
Jeszcze przejrzałam te funkcje, poprawiłam wartość zwracaną, bo również powinna być typem Wezel.  Jeszcze jedna uwaga, kiedy piszemy przy deklaracji struktury:

typedef struct nazwa_struktury
{
       jej definicja 
} Alias_struktury;

to wtedy zamiast "struct nazwa_struktury" możemy pisać zwyczajnie "Alias_struktury" (bez słowa struct) :) więc słowa "struct" również usunęłam, coby przejrzyście było :)
