### ISSUE TITLE
deklaracja struktur (drzewo, węzeł, wycieczka)

### ISSUE THREAD

**Issue by pieniadz1013** [pieniadz1013/INPG-baza-danych-wycieczki-#4]
Proponuję nazywać zmienne po polsku (drzewo, węzeł, korzeń) jeśli wolicie po angielsku, to możemy zmienić

**Comment by pieniadz1013** [comment]
zostawiam do napisania strukturę typ, dotyczącą wycieczki, tym zajmiemy się później

**Comment by JestemAnia** [comment]
Żyjemy w Polsce- nazywajmy więc po polsku. Ja się zwyczajnie dostosowałam do kodu Patrycji :) Powinniśmy najpierw zadeklarować struktury, wtedy nie byłoby takich niejasności.

**Comment by patsaf** [comment]
Popieram, na początku przydałaby się ta struktura. Oszczędziłoby nam to edytowania nazw później :)

**Comment by patsaf** [comment]
Poza tym, po czym sortujemy drzewo? Po cenie czy kraju?

**Comment by patsaf** [comment]
Hm, sensowniej chyba po kraju (chyba rozmawiam sama ze sobą)

**Comment by pieniadz1013** [comment]
Ja bym posortował po cenie (będzie trochę łatwiej chyba, poza tym klient będzie mógł sobie dostosować cenę do swoich możliwości) a oprócz tego napiszemy funkcję dzieki której będzie można wyszukać wycieczki do danego kraju

**Comment by JestemAnia** [comment]
Przepraszam, ale głosuję za tym, żebyśmy sortowali po cenie. Wydaje mi się, że tak będzie prościej

**Comment by patsaf** [comment]
Ok, niech będzie po cenie

**Comment by patsaf** [comment]
W takim razie proponuje funkcje wypisującą po cenie (bo to po prostu inorder, który już dziś wrzuciłam) zamienić na funkcje wypisującą po kraju
